from fastapi import APIRouter, Depends
from fastapi.responses import HTMLResponse
from sqlalchemy.orm import Session
from sqlalchemy import func
from datetime import datetime

from app.core.database import get_db
from app.models.student import Student
from app.models.system import User
from app.models.academic import Grade, AttendanceRecord
from app.core import security

router = APIRouter()

@router.get("/download", response_class=HTMLResponse)
def download_report(
    current_user: User = Depends(security.RequireRole(["admin", "pedagogical_manager"])),
    db: Session = Depends(get_db)
):
    """
    Generates a professional HTML report of the pedagogical KPIs and at-risk students.
    Restricted to Admins and Pedagogical Managers.
    """
    # 1. Calculate Global Stats
    total_students = db.query(func.count(Student.id)).scalar() or 0
    overall_average = db.query(func.avg(Grade.score)).filter(Grade.is_absent == False).scalar() or 0.0

    # Calculate Pass Rate (Average >= 10)
    student_avgs = db.query(Grade.student_id, func.avg(Grade.score).label("avg")).filter(Grade.is_absent == False).group_by(Grade.student_id).subquery()
    passing_students = db.query(func.count(student_avgs.c.student_id)).filter(student_avgs.c.avg >= 10.0).scalar() or 0
    pass_rate = (passing_students / total_students * 100) if total_students > 0 else 0.0

    # 2. Fetch At-Risk Students
    absence_sub = db.query(AttendanceRecord.student_id, func.count(AttendanceRecord.id).label("abs_count")).filter(AttendanceRecord.status == "Absent").group_by(AttendanceRecord.student_id).subquery()

    results = db.query(
        Student.id, User.first_name, User.last_name,
        func.coalesce(student_avgs.c.avg, 0.0).label("avg"),
        func.coalesce(absence_sub.c.abs_count, 0).label("abs")
    ).join(User, Student.user_id == User.id)\
     .outerjoin(student_avgs, Student.id == student_avgs.c.student_id)\
     .outerjoin(absence_sub, Student.id == absence_sub.c.student_id)\
     .filter((student_avgs.c.avg < 10.0) | (absence_sub.c.abs_count > 3)).all()

    # 3. Build HTML Table Rows
    at_risk_rows = ""
    for r in results:
        if r.avg < 10 and r.abs > 3:
            rec = "Urgent 1-on-1 meeting & probation warning"
        elif r.avg < 10:
            rec = "Peer-tutoring recommended"
        else:
            rec = "Send attendance notification"
            
        at_risk_rows += f"""
            <tr>
                <td>{r.first_name} {r.last_name}</td>
                <td>{round(r.avg, 2)}</td>
                <td>{r.abs}</td>
                <td>{rec}</td>
            </tr>
        """

    if not at_risk_rows:
        at_risk_rows = "<tr><td colspan='4' style='text-align: center;'>No at-risk students found.</td></tr>"

    timestamp = datetime.now().strftime("%B %d, %Y at %H:%M:%S")

    # 4. Generate Professional HTML
    html_content = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>EduTrack Pedagogical Report</title>
        <style>
            body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; color: #333; margin: 40px; background-color: #fff; }}
            h1 {{ color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 10px; margin-bottom: 5px; }}
            .header-info {{ font-size: 14px; color: #7f8c8d; margin-bottom: 30px; font-style: italic; }}
            
            .kpi-container {{ display: flex; gap: 20px; margin-bottom: 40px; }}
            .kpi-card {{ background-color: #f8f9fa; border-left: 5px solid #3498db; border-radius: 6px; padding: 20px; flex: 1; text-align: center; box-shadow: 0 2px 5px rgba(0,0,0,0.05); }}
            .kpi-value {{ font-size: 32px; font-weight: bold; color: #2c3e50; margin-bottom: 5px; }}
            .kpi-label {{ font-size: 13px; color: #7f8c8d; text-transform: uppercase; letter-spacing: 1px; font-weight: 600; }}
            
            h2 {{ color: #2c3e50; margin-top: 40px; font-size: 22px; }}
            
            table {{ width: 100%; border-collapse: collapse; margin-top: 15px; box-shadow: 0 2px 5px rgba(0,0,0,0.05); }}
            th, td {{ padding: 14px 15px; text-align: left; border-bottom: 1px solid #eaeaea; }}
            th {{ background-color: #2c3e50; color: white; font-weight: 500; text-transform: uppercase; font-size: 14px; letter-spacing: 0.5px; }}
            tr:hover {{ background-color: #f5f9fc; }}
            tr:nth-child(even) {{ background-color: #fafafa; }}
            
            .footer {{ margin-top: 50px; text-align: center; font-size: 12px; color: #95a5a6; border-top: 1px solid #eaeaea; padding-top: 20px; }}
        </style>
    </head>
    <body>
        <h1>EduTrack Pedagogical Report</h1>
        <div class="header-info">Generated by {current_user.first_name} {current_user.last_name} on {timestamp}</div>
        
        <div class="kpi-container">
            <div class="kpi-card">
                <div class="kpi-value">{total_students}</div>
                <div class="kpi-label">Total Students</div>
            </div>
            <div class="kpi-card">
                <div class="kpi-value">{round(overall_average, 2)} / 20</div>
                <div class="kpi-label">Overall Average</div>
            </div>
            <div class="kpi-card">
                <div class="kpi-value">{round(pass_rate, 2)}%</div>
                <div class="kpi-label">Global Pass Rate</div>
            </div>
        </div>

        <h2>Students Requiring Pedagogical Intervention</h2>
        <table>
            <thead>
                <tr>
                    <th>Student Name</th>
                    <th>Average Grade</th>
                    <th>Total Absences</th>
                    <th>Actionable Recommendation</th>
                </tr>
            </thead>
            <tbody>
                {at_risk_rows}
            </tbody>
        </table>
        
        <div class="footer">
            EduTrack Analytics Platform - Automated Reporting System
        </div>
    </body>
    </html>
    """
    return HTMLResponse(content=html_content)
