"""add_verification_code_columns

Revision ID: 24b00ba8f0cd
Revises: 8d603c532805
Create Date: 2026-06-08 15:14:16.814784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24b00ba8f0cd'
down_revision: Union[str, Sequence[str], None] = '8d603c532805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('verification_code_expires', sa.DateTime(), nullable=True))
    op.drop_column('users', 'two_factor_expires')
    op.drop_column('users', 'two_factor_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('two_factor_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('two_factor_expires', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('users', 'verification_code_expires')
    op.drop_column('users', 'verification_code')
    # ### end Alembic commands ###
