"""add_2fa_code_columns

Revision ID: 8d603c532805
Revises: fb68373a72f7
Create Date: 2026-06-08 11:02:18.818142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d603c532805'
down_revision: Union[str, Sequence[str], None] = 'fb68373a72f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('two_factor_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('two_factor_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'two_factor_expires')
    op.drop_column('users', 'two_factor_code')
    # ### end Alembic commands ###
