"""add_2fa_toggle_to_users

Revision ID: fb68373a72f7
Revises: 5de74d967482
Create Date: 2026-06-06 23:44:17.839251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb68373a72f7'
down_revision: Union[str, Sequence[str], None] = '5de74d967482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_2fa_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_2fa_enabled')
    # ### end Alembic commands ###
